server:
  port: 8019
spring:
  application:
    name: GestUser
  data:
    mongodb:
      authentication-database: admin
      database: ms-users
      host: 192.168.99.100
      password: 12345678
      port: 37017
      username: antonio
