# ==============================================================
# = Articoli Web Service con Autenticazione JWT
# ==============================================================

server:
  port: 5051

spring:
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
  datasource:
    initialization-mode: always
    password: 123_Stella
    platform: postgres
    url: jdbc:postgresql://192.168.99.100:5433/Alphashop    
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    
# ==============================================================
# = Proprietà Servizio gestUser
# ==============================================================
gestuser:
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: ReadUser
  password: BimBumBam_2018
  
# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    uri: /auth
    refresh: /refresh
    header: Authorization
    prefix: Bearer 
    expiration: 86400
    secret: 123_Stella
  

